# Generated by rust2rpm
%bcond_without check

%global crate fd-find

Name:           %{crate}
Version:        4.0.0
Release:        2%{?dist}
Summary:        fd is a simple, fast and user-friendly alternative to find.

License:        MIT
URL:            https://crates.io/crates/fd-find
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

Patch0:         fd-find-4.0.0-fix_metadata.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(ansi_term) >= 0.10.0 with crate(ansi_term) < 0.11.0)
BuildRequires:  (crate(atty) >= 0.2.0 with crate(atty) < 0.3.0)
BuildRequires:  (crate(clap) >= 2.26.0 with crate(clap) < 3.0.0)
BuildRequires:  (crate(ignore) >= 0.2.0 with crate(ignore) < 0.3.0)
BuildRequires:  (crate(num_cpus) >= 1.6.2 with crate(num_cpus) < 2.0.0)
BuildRequires:  (crate(regex) >= 0.2.0 with crate(regex) < 0.3.0)
# [build-dependencies]
BuildRequires:  (crate(clap) >= 2.26.0 with crate(clap) < 3.0.0)
%if %{with check}
# [dev-dependencies]
BuildRequires:  (crate(diff) >= 0.1.0 with crate(diff) < 0.2.0)
BuildRequires:  (crate(tempdir) >= 0.3.0 with crate(tempdir) < 0.4.0)
%endif
Requires:       bash-completion

%description
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

# bash completion
install -D -p -m 644 target/release/build/%{name}-*/out/fd.bash-completion \
    %{buildroot}%{_datadir}/bash-completion/completions/fd

# fish completion
install -D -p -m 644 target/release/build/%{name}-*/out/fd.fish \
    %{buildroot}%{_datadir}/fish/vendor_completions.d/fd.fish

# zsh completion
install -D -p -m 644 target/release/build/%{name}-*/out/_fd \
    %{buildroot}%{_datadir}/zsh/vendor-completions/_fd

%if %{with check}
%check
%cargo_test
%endif

%files
%doc README.md
%license LICENSE
%{_bindir}/fd
%{_datadir}/bash-completion/completions/fd
%dir %{_datadir}/fish
%dir %{_datadir}/fish/vendor_completions.d
%{_datadir}/fish/vendor_completions.d/fd.fish
%dir %{_datadir}/zsh
%dir %{_datadir}/zsh/vendor-completions
%{_datadir}/zsh/vendor-completions/_fd

%changelog
* Sat Oct 14 2017 Robert-André Mauchin <zebob.m@gmail.com> - 4.0.0-2
- Fix directories ownership
* Sun Oct 08 2017 Robert-André Mauchin <zebob.m@gmail.com> - 4.0.0-1
- Initial package
