# Generated by rust2rpm
%bcond_without check

%global crate oxipng

Name:           %{crate}
Version:        0.17.2
Release:        1%{?dist}
Summary:        A lossless PNG compression optimizer

License:        MIT
URL:            https://crates.io/crates/oxipng
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

Patch0:         oxipng-0.17.2-fix_metadata.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(bit-vec) >= 0.4.2 with crate(bit-vec) < 0.5.0)
BuildRequires:  (crate(byteorder) >= 1.0.0 with crate(byteorder) < 2.0.0)
BuildRequires:  (crate(clap) >= 2.10.0 with crate(clap) < 3.0.0)
BuildRequires:  (crate(crc) >= 1.2.0 with crate(crc) < 2.0.0)
BuildRequires:  ((crate(image) >= 0.17.0 with crate(image) < 0.18.0) with crate(image/png_codec))
BuildRequires:  (crate(itertools) >= 0.7.0 with crate(itertools) < 0.8.0)
BuildRequires:  (crate(libc) >= 0.2.4 with crate(libc) < 0.3.0)
BuildRequires:  (crate(miniz-sys) >= 0.1.7 with crate(miniz-sys) < 0.2.0)
BuildRequires:  (crate(num_cpus) >= 1.0.0 with crate(num_cpus) < 2.0.0)
BuildRequires:  (crate(rayon) >= 0.8.1 with crate(rayon) < 0.9.0)
BuildRequires:  (crate(regex) >= 0.2.0 with crate(regex) < 0.3.0)
BuildRequires:  (crate(zopfli) >= 0.3.4 with crate(zopfli) < 0.4.0)

%description
%{summary}.

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel
A lossless PNG compression optimizer.

This package contains library source intended for building other packages
which use %{crate} from crates.io.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files       -n %{crate}
%doc CHANGELOG.md README.md
%license LICENSE
%{_bindir}/oxipng

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%changelog
* Sat Oct 28 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0.17.2-1
- Initial package
