Name:           perl-Authen-DecHpwd
Version:        2.007
Release:        1%{?dist}
Summary:        DEC VMS password hashing
License:        GPLv2+
URL:            http://search.cpan.org/dist/Authen-DecHpwd/
Source0:        http://www.cpan.org/authors/id/Z/ZE/ZEFRAM/Authen-DecHpwd-%{version}.tar.gz
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(constant)
BuildRequires:  perl(Data::Integer) >= 0.003
BuildRequires:  perl(Digest::CRC) >= 0.14
BuildRequires:  perl(Exporter)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(parent)
BuildRequires:  perl(Scalar::String)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod::Coverage)
BuildRequires:  perl(Test::Pod)
BuildRequires:  perl(warnings)
BuildRequires:  perl(XSLoader)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module implements the SYS$HASH_PASSWORD password hashing function from
VMS (also known as LGI$HPWD), and some associated VMS username and password
handling functions.

%prep
%autosetup -n Authen-DecHpwd-%{version}

%build
%{__perl} Build.PL --installdirs=vendor --optimize="$RPM_OPT_FLAGS"
./Build

%install
./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -delete
%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%files
%doc Changes META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Authen*
%{_mandir}/man3/*

%changelog
* Sun Dec 03 2017 Robert-André Mauchin <zebob.m@gmail.com> - 2.007-1
- Specfile autogenerated by cpanspec 1.78.
