Name:           perl-Test-SQL-Data
Version:        0.0.6
Release:        1%{?dist}
Summary:        Helps running SQL tests: database preparing and result matching
License:        GPL+ or Artistic
URL:            https://github.com/frankiejol/Test-SQL-Data
Source0:        %{url}/archive/%{version}/%{name}-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(Carp)
BuildRequires:  perl(DBIx::Connector) >= 0.4.5
BuildRequires:  perl(DBD::SQLite) >= 1.20
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Path)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Perl::Critic)
BuildRequires:  perl(Test::Pod::Coverage) >= 1.04
BuildRequires:  perl(Test::Pod) >= 1.14
BuildRequires:  perl(warnings)
BuildRequires:  perl(YAML)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The purpose of Test::SQL::Data is to give your module a clean database to
work with. When the module loads it prepares the database. You can have it
empty or pre-load some SQL code before running your tests. Then you can use
the module again to check if your expected results match the contents of
the tables of the database.

%prep
%autosetup -n Test-SQL-Data-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
%make_build

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc INSTALL.md README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Dec 04 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0.0.6-1
- Specfile autogenerated by cpanspec 1.78.
