Name:           perl-MooseX-Types-NetAddr-IP
Version:        0.07
Release:        1%{?dist}
Summary:        NetAddr::IP related types and coercions for Moose
License:        GPL+ or Artistic
URL:            http://search.cpan.org/dist/MooseX-Types-NetAddr-IP/
Source0:        http://www.cpan.org/authors/id/T/TC/TCAINE/MooseX-Types-NetAddr-IP-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Runtime) >= 0.014
BuildRequires:  perl(Moose) >= 0.41
BuildRequires:  perl(MooseX::Types) >= 0.19
BuildRequires:  perl(namespace::clean) >= 0.08
BuildRequires:  perl(NetAddr::IP)
BuildRequires:  perl(Test::Exception)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This package provides internet address types for Moose.

%prep
%autosetup -n MooseX-Types-NetAddr-IP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
%make_build

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Dec 04 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0.07-1
- Specfile autogenerated by cpanspec 1.78.
