Name:           ravada
Version:        0.2.10
Release:        1%{?dist}
Summary:        Remote Virtual Desktops Manager
License:        AGPLv3
URL:            https://ravada.upc.edu/
Source0:        https://github.com/UPC/ravada/archive/v%{version}/%{name}-%{version}.tar.gz

# https://github.com/UPC/ravada/pull/498
Patch0:         ravada-0.2.10_fix_permissions.patch

BuildArch:      noarch
%{?systemd_requires}
BuildRequires:  systemd
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(Authen::Passphrase)
BuildRequires:  perl(DBD::SQLite)
BuildRequires:  perl(DBD::MySQL)
BuildRequires:  perl(DBIx::Connector)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Image::Magick)
BuildRequires:  perl(IO::Interface)
BuildRequires:  perl(IPC::Run3)
BuildRequires:  perl(IPTables::ChainMgr)
BuildRequires:  perl(JSON::XS)
BuildRequires:  perl(Locale::Maketext::Lexicon)
BuildRequires:  perl(Mojolicious) >= 6.15
BuildRequires:  perl(Mojolicious::Plugin::I18N)
BuildRequires:  perl(Mojolicious::Plugin::RenderFile)
BuildRequires:  perl(Moose)
BuildRequires:  perl(MooseX::Types::NetAddr::IP)
BuildRequires:  perl(Net::DNS)
BuildRequires:  perl(Net::LDAP)
BuildRequires:  perl(Sys::Statistics::Linux)
BuildRequires:  perl(Sys::Virt)
BuildRequires:  perl(Test::Pod::Coverage)
BuildRequires:  perl(Test::Perl::Critic)
BuildRequires:  perl(Test::SQL::Data)
BuildRequires:  perl(XML::LibXML)
BuildRequires:  perl(YAML)
# For tests
BuildRequires:  iptables
BuildRequires:  libvirt
BuildRequires:  libvirt-daemon-kvm
BuildRequires:  libvirt-daemon-lxc
BuildRequires:  mariadb-common
BuildRequires:  qemu-img
BuildRequires:  wget
Requires:       iptables
Requires:       libvirt
Requires:       libvirt-daemon-kvm
Requires:       libvirt-daemon-lxc
Requires:       mariadb-common
Requires:       qemu-img
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires(pre):  shadow-utils
Recommends:     virt-viewer

%description
Ravada is a software that allows the user to connect to a remote virtual 
desktop.

In the current release we use the KVM Hypervisors: KVM as the backend for the 
Virtual Machines. LXC support is currently in development.

%prep
%autosetup -p1 -n %{name}-%{version}

# Fedora doesn't ship kvm-spice but kvm
find . -type f -name "*.xml" -exec sed -i 's|kvm-spice|kvm|g' {} ';'

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
%make_build

%install
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

rm $RPM_BUILD_ROOT%{perl_vendorlib}/rvd_front.pl
install -Dpm 0755 rvd_front.pl $RPM_BUILD_ROOT%{_sbindir}/rvd_back.pl
install -Dpm 0755 bin/rvd_back.pl  $RPM_BUILD_ROOT%{_sbindir}/rvd_front.pl
install -Dpm 0644 etc/ravada.conf $RPM_BUILD_ROOT%{_sysconfdir}/ravada.conf
install -Dpm 0644 etc/rvd_front.conf.example $RPM_BUILD_ROOT%{_sysconfdir}/rvd_front.conf
install -Dpm 0644 etc/systemd/rvd_back.service $RPM_BUILD_ROOT%{_unitdir}/rvd_back.service
install -Dpm 0644 etc/systemd/rvd_front.service $RPM_BUILD_ROOT%{_unitdir}/rvd_front.service
mkdir -p $RPM_BUILD_ROOT%{_localstatedir}/lib/%{name}
cp -aR etc/xml $RPM_BUILD_ROOT%{_localstatedir}/lib/%{name}/
mkdir -p $RPM_BUILD_ROOT%{_datadir}/%{name}
cp -aR public $RPM_BUILD_ROOT%{_datadir}/%{name}/
cp -aR templates $RPM_BUILD_ROOT%{_datadir}/%{name}/

#Fix shebang
sed -i '1s/env //' $RPM_BUILD_ROOT%{_sbindir}/rvd_back.pl
sed -i '1s/env //' $RPM_BUILD_ROOT%{_sbindir}/rvd_front.pl

%check
# t/vm/20_base.t (Wstat: 256 Tests: 23 Failed: 1)
# Failed test:  23
rm t/vm/20_base.t
make test

%pre
getent group ravada >/dev/null || groupadd -r ravada
getent passwd ravada >/dev/null || \
    useradd -r -g ravada -d %{_localstatedir}/lib/ravada -s /sbin/nologin \
    -c "Ravada user account" ravada
exit 0

%post
%systemd_post rvd_back.service
%systemd_post rvd_front.service

%preun
%systemd_preun rvd_back.service
%systemd_preun rvd_front.service

%postun
%systemd_postun_with_restart rvd_back.service
%systemd_postun_with_restart rvd_front.service

%files
%doc CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md README.md sql
%license LICENSE
%{_sbindir}/rvd_back.pl
%{_sbindir}/rvd_front.pl
%{perl_vendorlib}/*
%config(noreplace) %{_sysconfdir}/*.conf
%{_datadir}/%{name}/
%{_localstatedir}/lib/%{name}/
%{_mandir}/man3/*
%{_unitdir}/*.service

%changelog
* Mon Dec 04 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0.2.10-1
- Specfile autogenerated by cpanspec 1.78.
