# Generated by rust2rpm
%bcond_without check

%global crate parallel

Name:           rust-%{crate}
Version:        0.11.3
Release:        1%{?dist}
Summary:        Command-line CPU load balancer for executing jobs in parallel

License:        MIT
URL:            https://crates.io/crates/parallel
Source0:        https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

Patch0:         parallel-0.11.3-fix_metadata.patch

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
# [dependencies]
BuildRequires:  (crate(arrayvec) >= 0.4.0 with crate(arrayvec) < 0.5.0)
BuildRequires:  (crate(itoa) >= 0.3.0 with crate(itoa) < 0.4.0)
BuildRequires:  (crate(num_cpus) >= 1.5.0 with crate(num_cpus) < 2.0.0)
BuildRequires:  (crate(numtoa) >= 0.0.0 with crate(numtoa) < 0.1.0)
BuildRequires:  (crate(permutate) >= 0.3.0 with crate(permutate) < 0.4.0)
BuildRequires:  (crate(smallvec) >= 0.4.0 with crate(smallvec) < 0.5.0)
BuildRequires:  (crate(sys-info) >= 0.5.0 with crate(sys-info) < 0.6.0)
BuildRequires:  (crate(time) >= 0.1.0 with crate(time) < 0.2.0)
BuildRequires:  (crate(wait-timeout) >= 0.1.0 with crate(wait-timeout) < 0.2.0)

%description
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%doc README.md
%license LICENSE
%{_bindir}/parallel

%changelog
* Sat Oct 14 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0.11.3-1
- Initial package
